server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: auth-service

  config:
    import: optional:configserver:http://localhost:9095

app:
  seeddata:
    email1: meghna@email.com
    email2: john@email.com
    password1: meghna@123
    password2: john@123
    role1: USER
    role2: ADMIN
    name1: Meghna
    name2: John
    logMessage: Loaded users...
  jwttoken:
    message: Login Successful
  controller:
    exception:
      message1: Id and Password Empty
      message2: Id and Password not found
      message3: Id and Password invalid
  service:
    message1: User Already Exists
    message2: Invalid Id and Password

management:
  endpoint:
    web:
      exposure:
        include=*: